name: 'Set up vcpkg'
inputs:
  run-setup:
    description: Set up vcpkg root directory
    required: false
    default: 'true'
  vcpkg-root:
    description: Vcpkg root directory
    required: false
    default: ''
  binary-cache-path:
    description: 'Vcpkg binary cache path'
    required: false
    default: ''
  save-cache:
    description: 'Enable cache saving'
    required: false
    default: 'true'
  cache-key-tag:
    description: 'Addition cache key tag to differentiate between cache entries with same RUNNER_OS'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
