name: 'Set up vcpkg'
inputs:
  run-install:
    description: Run vcpkg install command
    required: false
    default: 'false'
  triplet:
    description: 'Vcpkg triplet (required when run-install is true)'
    required: false
    default: ''
  install-features:
    description: 'Vcpkg manifest features'
    required: false
    default: ''
  install-clean-buildtrees:
    description: 'Clean buildtrees after building each package'
    required: false
    default: 'true'
  install-clean-packages:
    description: 'Clean packages after building each package'
    required: false
    default: 'true'
  install-clean-downloads:
    description: 'Clean downloads after building each package'
    required: false
    default: 'false'
  save-cache:
    description: 'Enable cache saving'
    required: false
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
